repoComments = {
    "Officer, this must be a mistake. I've been making my payments on time!",
    "Is there any way we can work this out? I really need my car for work.",
    "Can you give me a little more time to make the payment? I promise I'll get it sorted.",
    "I had no idea it had come to this. Can you call the repo company and ask them to stop?",
    "Please, officer, I have important documents in my car. Can I get them out before you take it?",
    "I can't believe this is happening. I'll lose my job without my car.",
    "Is there any way to avoid this going on my credit? It'll ruin me.",
    "I'm willing to make a partial payment right now if that helps.",
    "Can you tell the repo guy to be careful with my car? It's in great condition.",
    "I understand it's your job, but please have some empathy. This is really tough for me.",
    "I promise I'll catch up on the payments soon. I just need a little more time.",
    "Is there any way you can give me a ride home? I don't know how I'll get back.",
    "Officer, my family is going through a tough time. Please, reconsider this.",
    "I'm a single parent. Taking my car will make it impossible for me to pick up my kids.",
    "Can you at least give me a few minutes to get my personal belongings from the car?",
    "I'll lose my job if I can't get to work. Can you help me out here?",
    "I've been hospitalized and couldn't make the payment. Please, understand my situation.",
    "I'll do anything to avoid this. Please, let's find a solution together.",
    "I'm just a few days late with the payment. Can you make an exception this time?",
    "Is there a way to negotiate with the bank or repo company right now?",
    "I've been a loyal customer. Can you talk to your superior about this?",
    "This car is my lifeline. Taking it will devastate me.",
    "I'm begging you, officer, can you find it in your heart to help me out?",
    "I promise I'll make the payment tomorrow. Please, don't take my car today.",
    "Officer, I've fallen on hard times. Is there any way to avoid this?",
    "I'm willing to work something out. Can we talk to the repo company together?",
    "I'm not trying to run away from my responsibilities. Please give me a chance.",
    "I didn't receive any warning about this. Can we sort this out right now?",
    "I have nowhere else to turn. Please, have mercy.",
    "Taking my car will only make things worse. Can we find a different solution?",
    "I'm barely making ends meet. Taking my car will ruin me financially.",
    "Officer, I have an emergency medical condition. Taking my car will put my life at risk.",
    "I'll pay extra interest or penalties. Just don't take my car today.",
    "Can you speak to the repo company about this? I can't lose my car.",
    "Officer, I'm going through a divorce. This is the last thing I need right now.",
    "I promise I'll get a second job to cover the payments. Please reconsider.",
    "I'll make a down payment right now. Please, let me keep my car.",
    "Is there a local charity or organization that can help me make the payment?",
    "My car is essential for my livelihood. Please, don't take it away.",
    "Officer, I'll do community service or volunteer work. Just give me a chance.",
    "I've had this car for years. It means the world to me. Can we find another way?",
    "Taking my car will affect my ability to take care of my elderly parents.",
    "I'm willing to meet with a financial advisor to work out a payment plan.",
    "Please, officer, consider the impact this will have on my children.",
    "I'm just a bit behind on my payments. Can we resolve this without the repo?",
    "Is there any way to negotiate the repossession fees? I can't afford them.",
    "I'll sign any legal agreement to ensure I make my payments. Please, reconsider.",
    "Taking my car will make it impossible for me to get groceries and essentials.",
    "I'll sell personal belongings to make the payment. Please, give me more time.",
    "Officer, this car is my only mode of transportation. Please, think this through.",
    "I don't care about your rules! You're ruining my life!",
    "You have no idea what I've been through. You think you're helping? You're not!",
    "This is an abuse of power, officer. You should be ashamed of yourself.",
    "Why don't you go after real criminals instead of innocent people like me?",
    "You're just doing this for the money, aren't you? You don't care about the people.",
}

repoCommentsDriver = {
    -- Neutral Responses
    "I see you're just doing your job.",
    "Can we discuss this situation?",
    "I knew this was coming eventually.",
    "I'll need to remove my personal items first.",
    "Is there a way to delay this for a bit?",
    "I'll contact the finance company to sort this out.",
    "I'll call my lawyer about this.",
    "Can you give me a moment to say goodbye?",
    "This is unfortunate, but I understand.",
    "I'll deal with this through the proper channels.",
    "I hope the process goes smoothly.",
    "I'll need to find alternate transportation.",
    "This is frustrating, but it is what it is.",
    "I'll take care of my remaining belongings.",
    "I'll comply with your instructions.",
    "I hope you don't damage my car.",
    "I need to make some calls to sort this out.",
    "Can you tell me where my car will be taken?",
    "I'll need to cancel my plans for the day.",
    "I'll reach out to the bank about this.",
    "I understand this isn't your fault.",
    "I hope the process is done quickly.",
    "Can I at least get my child's car seat?",
    "I didn't expect it to come to this.",
    "I'll get in touch with my insurance company.",
    "This isn't a great start to the day.",
    "I'll cooperate as best as I can.",
    "Can you provide me with the repo company's details?",
    "I'll have to find alternative transportation.",
    "I'll handle this responsibly.",
    "I have to inform my employer about this.",
    "I need to make arrangements for my pet.",
    "I should've been more financially responsible.",
    "I'll need to find a way to work without my car.",
    "I can't afford to lose my job right now.",
    "I'll contact the bank about this situation.",
    "I'll need to cancel my appointments.",
    "I hope I can get my car back soon.",
    "I wish this could've been avoided.",
    "I'll take care of my car loan immediately.",
    "I'll make sure my car payments are up to date.",
    "I hope this process is as painless as possible.",
    "I'll deal with this inconvenience.",
    "I'll check with my local transit options.",
    "I'll consider carpooling for now.",
    "I'll get a rental car for the time being.",
    "I can't believe I let it come to this.",
    "I hope the bank can be flexible.",
    "I should've been more careful with my finances.",
    "I'll figure this out one step at a time.",

    -- Negative Responses
    "This is ridiculous, I won't let you take my car!",
    "You're the reason my life's falling apart!",
    "I'll make sure you regret doing this.",
    "You're just here to steal from hardworking folks.",
    "You must enjoy ruining people's lives, huh?",
    "This is a nightmare, and it's all your fault.",
    "I'll sue you for this, mark my words.",
    "You're just a heartless thief with a tow truck.",
    "You're scum for doing this to me.",
    "You're ruining my life, and it's unforgivable.",
    "You have no compassion, do you?",
    "I hope your day is as awful as mine now.",
    "This is the worst day of my life, thanks to you.",
    "You'll get what's coming to you, just wait.",
    "You're nothing but a repo vulture.",
    "I hope you get a taste of your own medicine.",
    "I'll make sure everyone knows what you did.",
    "You're a disgrace to your profession.",
    "I curse the day I ever crossed paths with you.",
    "You're a heartless, soulless person.",
    "I'll fight this until my last breath.",
    "You're going to pay for this, one way or another.",
    "You won't get away with this without consequences.",
    "This is a nightmare, and you're the monster in it.",
    "I'll make sure you regret this day.",
    "You're a heartless robot, not a human being.",
    "I'll make sure your reputation is ruined.",
    "You're scum for doing this to me.",
    "I'll never forgive you for this.",
    "You have no soul to speak of.",
    "I hope you lose everything just like I am.",
    "You're just a puppet of the finance companies.",
    "I'll fight this with everything I've got.",
    "You're a disgrace to humanity.",
    "I'll make sure your life is just as miserable as mine now.",
    "You're nothing but a soulless automaton."
}

repoResponses = {
    "Is there anything I can do to stop this?",
    "I understand the situation, but this is really tough.",
    "I'll cooperate, but I'm not happy about this.",
    "This is not a great start to my day, officer.",
    "I'm shocked by this turn of events.",
    "I can't believe it has come to this.",
    "I'm not sure how I'll manage without my car.",
    "This is a real inconvenience for me.",
    "I never thought I'd see this day.",
    "I suppose it was bound to happen eventually.",
    "This is a major setback for me.",
    "I can't help but feel frustrated.",
    "This is unfair. I've been trying my best.",
    "I thought I had more time to sort this out.",
    "This is really putting me in a tough spot.",
    "I wish there were other options.",
    "I'll have to find a way to make do without the car.",
    "This is a terrible surprise to wake up to.",
    "I'll have to find alternative transportation now.",
    "I'm going to have to figure this out somehow.",
    "I'm disappointed, but I can't do much about it.",
    "I really needed my car for work.",
    "This is a serious hassle for me.",
    "I can't believe it has come to this point.",
    "This is incredibly frustrating.",
    "I can't afford to lose my car right now.",
    "This is causing a lot of stress for me.",
    "I'm going to miss my car more than I thought.",
    "I can't believe my car is being taken away.",
    "This feels like a punch in the gut.",
    "I'm not happy about this at all.",
    "I've been trying to make things right.",
    "I guess I should have seen this coming.",
    "I'm not sure how I'll manage without my car.",
    "I need to find a solution quickly.",
    "This is going to make my life so much harder.",
    "I'm going to have to make some big adjustments now.",
    "I can't help but feel angry about this.",
    "I really thought I had more time.",
    "This is a huge inconvenience for me.",
    "I don't know how I'll get by without my car.",
    "This is not what I needed right now.",
    "I'm not ready for this.",
    "I've been working to get back on my feet.",
    "I'm going to have to find another way to get around.",
    "I wish there were some leniency here.",
    "This is incredibly frustrating for me.",
}

positions = {
    {vector4(131.0, -1632.72, 28.83, 242.99), vector4(135.87, -1634.78, 29.29, 67.71)},
    {vector4(260.19, -1563.93, 28.58, 300.05), vector4(263.44, -1565.85, 29.26, 29.74)},
    {vector4(45.29, -1312.03, 28.84, 179.96), vector4(48.67, -1312.63, 29.29, 295.88)},
    {vector4(422.69, -1294.77, 29.84, 320.53), vector4(422.72, -1292.29, 30.26, 298.84)},
    {vector4(-612.72, -1210.91, 13.93, 313.15), vector4(-614.31, -1215.53, 14.15, 306.43)},
    {vector4(71.07, -593.15, 31.2, 69.19), vector4(69.41, -594.25, 31.63, 289.65)},
    {vector4(393.78, -649.65, 28.07, 270.7), vector4(396.74, -649.29, 28.5, 252.9)},
    {vector4(-485.54, -596.07, 30.76, 179.53), vector4(-485.09, -600.26, 31.17, 7.91)},
    {vector4(-409.76, -281.85, 34.82, 108.77), vector4(-407.77, -282.54, 35.09, 192.91)},
    {vector4(-1417.92, -642.2, 28.26, 211.77), vector4(-1410.48, -652.73, 28.67, 34.98)},
    {vector4(1104.63, -398.98, 67.41, 75.06),  vector4(1100.2, -401.57, 67.43, 340.81)}
}